using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class OrangePlayer : MonoBehaviour
{
    #region 逆
    [SerializeField] Rigidbody2D zt参 = null;
    [SerializeField] float ]t = 5f;
    [Header("铬D蔼"), Range(0, 20)]
    public int jumpHeight = 16;
    [Header("O_baOW")]
    public bool onGround = false;
    [Header("浪daO跋办:觳净Pb|")]
    public Vector2 groundOffset;
    public Vector2 groundRadius;
    #endregion

    #region ㄆン
    private void Update()
    {
        float ad = Input.GetAxis("Horizontal");

        Vector2 move;
        move.x = ad * ]t;
        move.y = zt参.velocity.y;

        Vector2 锣传y夹 = this.transform.TransformVector(move);

        zt参.velocity = 锣传y夹;

        Jump();
    }
    private void OnDrawGizmos()
    {
        Gizmos.color = new Color(1, 0, 0, 0.3f);
        Gizmos.DrawCube(
            transform.position + 
            transform.right * groundOffset.x + 
            transform.up * groundOffset.y,
            groundRadius);
    }
    #endregion

    #region よk
    private void Jump()
    {
        Collider2D groundHit = Physics2D.OverlapBox(
            transform.position +
            transform.right * groundOffset.x +
            transform.up * groundOffset.y,
            groundRadius, 0, 1 << 6);

        Debug.Log(groundHit);

        if (groundHit) onGround = true;
        else onGround = false;

        if(Input.GetKeyDown(KeyCode.UpArrow) && onGround)
        {
            zt参.velocity = new Vector2(zt参.velocity.x, jumpHeight);
        }
        if(Input.GetKeyUp(KeyCode.UpArrow) && zt参.velocity.y > 0f)
        {
            zt参.velocity = new Vector2(zt参.velocity.x, zt参.velocity.y * 0.5f);
        }
    }
    #endregion
}
